language: erlang
script: "make travis"
otp_release:
  - 17.1
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R16B
  - R15B02
  - R15B01
  - R15B
before_script: "sudo apt-get --yes --force-yes install libpam0g-dev"
